language: c
env:
  - RUN_TEST=false OCAML_VERSION=4.00.1
  - RUN_TEST=false OCAML_VERSION=4.01.0
  - RUN_TEST=true OCAML_VERSION=4.02.3
  - RUN_TEST=true OCAML_VERSION=4.03.0
  - RUN_TEST=true OCAML_VERSION=4.03.0+flambda
  - RUN_TEST=true OCAML_VERSION=4.04.0
  - RUN_TEST=true OCAML_VERSION=4.04.0+flambda
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlfind ocamlbuild
  - opam pin add -k git frogutils . --yes
install:
  - ./configure
  - make
script:
